[package]
name = "nwin"
version = "0.1.0"
authors = ["glacambre <code@lacamb.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = { git = "https://github.com/glacambre/neovim-lib" }
niri-ipc = "25.5.1"
home = "0.5.3"
fontconfig = "0.10.0"

[dependencies.sdl2]
version = "0.35.1"
features = ["ttf", "unsafe_textures"]
